#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicittApp.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DBMICITT")]
	public partial class sqlConnectionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_CONS_DPT(TBL_CONS_DPT instance);
    partial void UpdateTBL_CONS_DPT(TBL_CONS_DPT instance);
    partial void DeleteTBL_CONS_DPT(TBL_CONS_DPT instance);
    partial void InsertTBL_DIRECCIONE(TBL_DIRECCIONE instance);
    partial void UpdateTBL_DIRECCIONE(TBL_DIRECCIONE instance);
    partial void DeleteTBL_DIRECCIONE(TBL_DIRECCIONE instance);
    partial void InsertTBL_DOC(TBL_DOC instance);
    partial void UpdateTBL_DOC(TBL_DOC instance);
    partial void DeleteTBL_DOC(TBL_DOC instance);
    partial void InsertTBL_DPT(TBL_DPT instance);
    partial void UpdateTBL_DPT(TBL_DPT instance);
    partial void DeleteTBL_DPT(TBL_DPT instance);
    partial void InsertTBL_USUARIO(TBL_USUARIO instance);
    partial void UpdateTBL_USUARIO(TBL_USUARIO instance);
    partial void DeleteTBL_USUARIO(TBL_USUARIO instance);
    #endregion
		
		public sqlConnectionDataContext() : 
				base(global::MicittApp.DataAccess.Properties.Settings.Default.DBMICITTConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public sqlConnectionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public sqlConnectionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public sqlConnectionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public sqlConnectionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_CONS_DPT> TBL_CONS_DPTs
		{
			get
			{
				return this.GetTable<TBL_CONS_DPT>();
			}
		}
		
		public System.Data.Linq.Table<TBL_DIRECCIONE> TBL_DIRECCIONEs
		{
			get
			{
				return this.GetTable<TBL_DIRECCIONE>();
			}
		}
		
		public System.Data.Linq.Table<TBL_DOC> TBL_DOCs
		{
			get
			{
				return this.GetTable<TBL_DOC>();
			}
		}
		
		public System.Data.Linq.Table<TBL_DPT> TBL_DPTs
		{
			get
			{
				return this.GetTable<TBL_DPT>();
			}
		}
		
		public System.Data.Linq.Table<TBL_USUARIO> TBL_USUARIOs
		{
			get
			{
				return this.GetTable<TBL_USUARIO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_CONS_DPTS")]
	public partial class TBL_CONS_DPT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_IDENTIFICADOR;
		
		private int _ID_DPTO;
		
		private string _CREATEBY_CONS_DPT;
		
		private string _UPTATEBY_CONS_DPT;
		
		private bool _STATE_CONS_DPT;
		
		private System.DateTime _CREATEDATE_CONS_DPT;
		
		private EntitySet<TBL_DOC> _TBL_DOCs;
		
		private EntityRef<TBL_DPT> _TBL_DPT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_IDENTIFICADORChanging(string value);
    partial void OnID_IDENTIFICADORChanged();
    partial void OnID_DPTOChanging(int value);
    partial void OnID_DPTOChanged();
    partial void OnCREATEBY_CONS_DPTChanging(string value);
    partial void OnCREATEBY_CONS_DPTChanged();
    partial void OnUPTATEBY_CONS_DPTChanging(string value);
    partial void OnUPTATEBY_CONS_DPTChanged();
    partial void OnSTATE_CONS_DPTChanging(bool value);
    partial void OnSTATE_CONS_DPTChanged();
    partial void OnCREATEDATE_CONS_DPTChanging(System.DateTime value);
    partial void OnCREATEDATE_CONS_DPTChanged();
    #endregion
		
		public TBL_CONS_DPT()
		{
			this._TBL_DOCs = new EntitySet<TBL_DOC>(new Action<TBL_DOC>(this.attach_TBL_DOCs), new Action<TBL_DOC>(this.detach_TBL_DOCs));
			this._TBL_DPT = default(EntityRef<TBL_DPT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_IDENTIFICADOR", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_IDENTIFICADOR
		{
			get
			{
				return this._ID_IDENTIFICADOR;
			}
			set
			{
				if ((this._ID_IDENTIFICADOR != value))
				{
					this.OnID_IDENTIFICADORChanging(value);
					this.SendPropertyChanging();
					this._ID_IDENTIFICADOR = value;
					this.SendPropertyChanged("ID_IDENTIFICADOR");
					this.OnID_IDENTIFICADORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DPTO", DbType="Int NOT NULL")]
		public int ID_DPTO
		{
			get
			{
				return this._ID_DPTO;
			}
			set
			{
				if ((this._ID_DPTO != value))
				{
					if (this._TBL_DPT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_DPTOChanging(value);
					this.SendPropertyChanging();
					this._ID_DPTO = value;
					this.SendPropertyChanged("ID_DPTO");
					this.OnID_DPTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEBY_CONS_DPT", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string CREATEBY_CONS_DPT
		{
			get
			{
				return this._CREATEBY_CONS_DPT;
			}
			set
			{
				if ((this._CREATEBY_CONS_DPT != value))
				{
					this.OnCREATEBY_CONS_DPTChanging(value);
					this.SendPropertyChanging();
					this._CREATEBY_CONS_DPT = value;
					this.SendPropertyChanged("CREATEBY_CONS_DPT");
					this.OnCREATEBY_CONS_DPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPTATEBY_CONS_DPT", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string UPTATEBY_CONS_DPT
		{
			get
			{
				return this._UPTATEBY_CONS_DPT;
			}
			set
			{
				if ((this._UPTATEBY_CONS_DPT != value))
				{
					this.OnUPTATEBY_CONS_DPTChanging(value);
					this.SendPropertyChanging();
					this._UPTATEBY_CONS_DPT = value;
					this.SendPropertyChanged("UPTATEBY_CONS_DPT");
					this.OnUPTATEBY_CONS_DPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_CONS_DPT", DbType="Bit NOT NULL")]
		public bool STATE_CONS_DPT
		{
			get
			{
				return this._STATE_CONS_DPT;
			}
			set
			{
				if ((this._STATE_CONS_DPT != value))
				{
					this.OnSTATE_CONS_DPTChanging(value);
					this.SendPropertyChanging();
					this._STATE_CONS_DPT = value;
					this.SendPropertyChanged("STATE_CONS_DPT");
					this.OnSTATE_CONS_DPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE_CONS_DPT", DbType="DateTime NOT NULL")]
		public System.DateTime CREATEDATE_CONS_DPT
		{
			get
			{
				return this._CREATEDATE_CONS_DPT;
			}
			set
			{
				if ((this._CREATEDATE_CONS_DPT != value))
				{
					this.OnCREATEDATE_CONS_DPTChanging(value);
					this.SendPropertyChanging();
					this._CREATEDATE_CONS_DPT = value;
					this.SendPropertyChanged("CREATEDATE_CONS_DPT");
					this.OnCREATEDATE_CONS_DPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_CONS_DPT_TBL_DOC", Storage="_TBL_DOCs", ThisKey="ID_IDENTIFICADOR", OtherKey="ID_IDENTIFICADOR")]
		public EntitySet<TBL_DOC> TBL_DOCs
		{
			get
			{
				return this._TBL_DOCs;
			}
			set
			{
				this._TBL_DOCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_DPT_TBL_CONS_DPT", Storage="_TBL_DPT", ThisKey="ID_DPTO", OtherKey="ID_DPTO", IsForeignKey=true)]
		public TBL_DPT TBL_DPT
		{
			get
			{
				return this._TBL_DPT.Entity;
			}
			set
			{
				TBL_DPT previousValue = this._TBL_DPT.Entity;
				if (((previousValue != value) 
							|| (this._TBL_DPT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_DPT.Entity = null;
						previousValue.TBL_CONS_DPTs.Remove(this);
					}
					this._TBL_DPT.Entity = value;
					if ((value != null))
					{
						value.TBL_CONS_DPTs.Add(this);
						this._ID_DPTO = value.ID_DPTO;
					}
					else
					{
						this._ID_DPTO = default(int);
					}
					this.SendPropertyChanged("TBL_DPT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_DOCs(TBL_DOC entity)
		{
			this.SendPropertyChanging();
			entity.TBL_CONS_DPT = this;
		}
		
		private void detach_TBL_DOCs(TBL_DOC entity)
		{
			this.SendPropertyChanging();
			entity.TBL_CONS_DPT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_DIRECCIONES")]
	public partial class TBL_DIRECCIONE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_DIRECCION;
		
		private string _DESCRIP_DIR;
		
		private string _CREATEBY_DIR;
		
		private string _UPDATEBY_DIR;
		
		private bool _STATE_DIR;
		
		private System.DateTime _CREATEDATE_DIR;
		
		private EntitySet<TBL_DPT> _TBL_DPTs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DIRECCIONChanging(int value);
    partial void OnID_DIRECCIONChanged();
    partial void OnDESCRIP_DIRChanging(string value);
    partial void OnDESCRIP_DIRChanged();
    partial void OnCREATEBY_DIRChanging(string value);
    partial void OnCREATEBY_DIRChanged();
    partial void OnUPDATEBY_DIRChanging(string value);
    partial void OnUPDATEBY_DIRChanged();
    partial void OnSTATE_DIRChanging(bool value);
    partial void OnSTATE_DIRChanged();
    partial void OnCREATEDATE_DIRChanging(System.DateTime value);
    partial void OnCREATEDATE_DIRChanged();
    #endregion
		
		public TBL_DIRECCIONE()
		{
			this._TBL_DPTs = new EntitySet<TBL_DPT>(new Action<TBL_DPT>(this.attach_TBL_DPTs), new Action<TBL_DPT>(this.detach_TBL_DPTs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DIRECCION", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_DIRECCION
		{
			get
			{
				return this._ID_DIRECCION;
			}
			set
			{
				if ((this._ID_DIRECCION != value))
				{
					this.OnID_DIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._ID_DIRECCION = value;
					this.SendPropertyChanged("ID_DIRECCION");
					this.OnID_DIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIP_DIR", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DESCRIP_DIR
		{
			get
			{
				return this._DESCRIP_DIR;
			}
			set
			{
				if ((this._DESCRIP_DIR != value))
				{
					this.OnDESCRIP_DIRChanging(value);
					this.SendPropertyChanging();
					this._DESCRIP_DIR = value;
					this.SendPropertyChanged("DESCRIP_DIR");
					this.OnDESCRIP_DIRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEBY_DIR", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string CREATEBY_DIR
		{
			get
			{
				return this._CREATEBY_DIR;
			}
			set
			{
				if ((this._CREATEBY_DIR != value))
				{
					this.OnCREATEBY_DIRChanging(value);
					this.SendPropertyChanging();
					this._CREATEBY_DIR = value;
					this.SendPropertyChanged("CREATEBY_DIR");
					this.OnCREATEBY_DIRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATEBY_DIR", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string UPDATEBY_DIR
		{
			get
			{
				return this._UPDATEBY_DIR;
			}
			set
			{
				if ((this._UPDATEBY_DIR != value))
				{
					this.OnUPDATEBY_DIRChanging(value);
					this.SendPropertyChanging();
					this._UPDATEBY_DIR = value;
					this.SendPropertyChanged("UPDATEBY_DIR");
					this.OnUPDATEBY_DIRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_DIR", DbType="Bit NOT NULL")]
		public bool STATE_DIR
		{
			get
			{
				return this._STATE_DIR;
			}
			set
			{
				if ((this._STATE_DIR != value))
				{
					this.OnSTATE_DIRChanging(value);
					this.SendPropertyChanging();
					this._STATE_DIR = value;
					this.SendPropertyChanged("STATE_DIR");
					this.OnSTATE_DIRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE_DIR", DbType="DateTime NOT NULL")]
		public System.DateTime CREATEDATE_DIR
		{
			get
			{
				return this._CREATEDATE_DIR;
			}
			set
			{
				if ((this._CREATEDATE_DIR != value))
				{
					this.OnCREATEDATE_DIRChanging(value);
					this.SendPropertyChanging();
					this._CREATEDATE_DIR = value;
					this.SendPropertyChanged("CREATEDATE_DIR");
					this.OnCREATEDATE_DIRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_DIRECCIONE_TBL_DPT", Storage="_TBL_DPTs", ThisKey="ID_DIRECCION", OtherKey="ID_DIRECCION")]
		public EntitySet<TBL_DPT> TBL_DPTs
		{
			get
			{
				return this._TBL_DPTs;
			}
			set
			{
				this._TBL_DPTs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_DPTs(TBL_DPT entity)
		{
			this.SendPropertyChanging();
			entity.TBL_DIRECCIONE = this;
		}
		
		private void detach_TBL_DPTs(TBL_DPT entity)
		{
			this.SendPropertyChanging();
			entity.TBL_DIRECCIONE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_DOCS")]
	public partial class TBL_DOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_DOC;
		
		private string _ID_IDENTIFICADOR;
		
		private string _TITULO_DOC;
		
		private string _EMISOR_DOC;
		
		private string _DESTINATARIO_DOC;
		
		private System.DateTime _FECHA_DOC;
		
		private string _PRIORIDAD;
		
		private string _UBICACION;
		
		private string _CREATEBY_DOC;
		
		private string _UPDATEBY_DOC;
		
		private bool _STATE_DOC;
		
		private System.DateTime _CREATEDATE_DOC;
		
		private EntityRef<TBL_CONS_DPT> _TBL_CONS_DPT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DOCChanging(int value);
    partial void OnID_DOCChanged();
    partial void OnID_IDENTIFICADORChanging(string value);
    partial void OnID_IDENTIFICADORChanged();
    partial void OnTITULO_DOCChanging(string value);
    partial void OnTITULO_DOCChanged();
    partial void OnEMISOR_DOCChanging(string value);
    partial void OnEMISOR_DOCChanged();
    partial void OnDESTINATARIO_DOCChanging(string value);
    partial void OnDESTINATARIO_DOCChanged();
    partial void OnFECHA_DOCChanging(System.DateTime value);
    partial void OnFECHA_DOCChanged();
    partial void OnPRIORIDADChanging(string value);
    partial void OnPRIORIDADChanged();
    partial void OnUBICACIONChanging(string value);
    partial void OnUBICACIONChanged();
    partial void OnCREATEBY_DOCChanging(string value);
    partial void OnCREATEBY_DOCChanged();
    partial void OnUPDATEBY_DOCChanging(string value);
    partial void OnUPDATEBY_DOCChanged();
    partial void OnSTATE_DOCChanging(bool value);
    partial void OnSTATE_DOCChanged();
    partial void OnCREATEDATE_DOCChanging(System.DateTime value);
    partial void OnCREATEDATE_DOCChanged();
    #endregion
		
		public TBL_DOC()
		{
			this._TBL_CONS_DPT = default(EntityRef<TBL_CONS_DPT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DOC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_DOC
		{
			get
			{
				return this._ID_DOC;
			}
			set
			{
				if ((this._ID_DOC != value))
				{
					this.OnID_DOCChanging(value);
					this.SendPropertyChanging();
					this._ID_DOC = value;
					this.SendPropertyChanged("ID_DOC");
					this.OnID_DOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_IDENTIFICADOR", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string ID_IDENTIFICADOR
		{
			get
			{
				return this._ID_IDENTIFICADOR;
			}
			set
			{
				if ((this._ID_IDENTIFICADOR != value))
				{
					if (this._TBL_CONS_DPT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_IDENTIFICADORChanging(value);
					this.SendPropertyChanging();
					this._ID_IDENTIFICADOR = value;
					this.SendPropertyChanged("ID_IDENTIFICADOR");
					this.OnID_IDENTIFICADORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITULO_DOC", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TITULO_DOC
		{
			get
			{
				return this._TITULO_DOC;
			}
			set
			{
				if ((this._TITULO_DOC != value))
				{
					this.OnTITULO_DOCChanging(value);
					this.SendPropertyChanging();
					this._TITULO_DOC = value;
					this.SendPropertyChanged("TITULO_DOC");
					this.OnTITULO_DOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMISOR_DOC", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string EMISOR_DOC
		{
			get
			{
				return this._EMISOR_DOC;
			}
			set
			{
				if ((this._EMISOR_DOC != value))
				{
					this.OnEMISOR_DOCChanging(value);
					this.SendPropertyChanging();
					this._EMISOR_DOC = value;
					this.SendPropertyChanged("EMISOR_DOC");
					this.OnEMISOR_DOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESTINATARIO_DOC", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DESTINATARIO_DOC
		{
			get
			{
				return this._DESTINATARIO_DOC;
			}
			set
			{
				if ((this._DESTINATARIO_DOC != value))
				{
					this.OnDESTINATARIO_DOCChanging(value);
					this.SendPropertyChanging();
					this._DESTINATARIO_DOC = value;
					this.SendPropertyChanged("DESTINATARIO_DOC");
					this.OnDESTINATARIO_DOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_DOC", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_DOC
		{
			get
			{
				return this._FECHA_DOC;
			}
			set
			{
				if ((this._FECHA_DOC != value))
				{
					this.OnFECHA_DOCChanging(value);
					this.SendPropertyChanging();
					this._FECHA_DOC = value;
					this.SendPropertyChanged("FECHA_DOC");
					this.OnFECHA_DOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIORIDAD", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PRIORIDAD
		{
			get
			{
				return this._PRIORIDAD;
			}
			set
			{
				if ((this._PRIORIDAD != value))
				{
					this.OnPRIORIDADChanging(value);
					this.SendPropertyChanging();
					this._PRIORIDAD = value;
					this.SendPropertyChanged("PRIORIDAD");
					this.OnPRIORIDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UBICACION", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UBICACION
		{
			get
			{
				return this._UBICACION;
			}
			set
			{
				if ((this._UBICACION != value))
				{
					this.OnUBICACIONChanging(value);
					this.SendPropertyChanging();
					this._UBICACION = value;
					this.SendPropertyChanged("UBICACION");
					this.OnUBICACIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEBY_DOC", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string CREATEBY_DOC
		{
			get
			{
				return this._CREATEBY_DOC;
			}
			set
			{
				if ((this._CREATEBY_DOC != value))
				{
					this.OnCREATEBY_DOCChanging(value);
					this.SendPropertyChanging();
					this._CREATEBY_DOC = value;
					this.SendPropertyChanged("CREATEBY_DOC");
					this.OnCREATEBY_DOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATEBY_DOC", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string UPDATEBY_DOC
		{
			get
			{
				return this._UPDATEBY_DOC;
			}
			set
			{
				if ((this._UPDATEBY_DOC != value))
				{
					this.OnUPDATEBY_DOCChanging(value);
					this.SendPropertyChanging();
					this._UPDATEBY_DOC = value;
					this.SendPropertyChanged("UPDATEBY_DOC");
					this.OnUPDATEBY_DOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_DOC", DbType="Bit NOT NULL")]
		public bool STATE_DOC
		{
			get
			{
				return this._STATE_DOC;
			}
			set
			{
				if ((this._STATE_DOC != value))
				{
					this.OnSTATE_DOCChanging(value);
					this.SendPropertyChanging();
					this._STATE_DOC = value;
					this.SendPropertyChanged("STATE_DOC");
					this.OnSTATE_DOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE_DOC", DbType="DateTime NOT NULL")]
		public System.DateTime CREATEDATE_DOC
		{
			get
			{
				return this._CREATEDATE_DOC;
			}
			set
			{
				if ((this._CREATEDATE_DOC != value))
				{
					this.OnCREATEDATE_DOCChanging(value);
					this.SendPropertyChanging();
					this._CREATEDATE_DOC = value;
					this.SendPropertyChanged("CREATEDATE_DOC");
					this.OnCREATEDATE_DOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_CONS_DPT_TBL_DOC", Storage="_TBL_CONS_DPT", ThisKey="ID_IDENTIFICADOR", OtherKey="ID_IDENTIFICADOR", IsForeignKey=true)]
		public TBL_CONS_DPT TBL_CONS_DPT
		{
			get
			{
				return this._TBL_CONS_DPT.Entity;
			}
			set
			{
				TBL_CONS_DPT previousValue = this._TBL_CONS_DPT.Entity;
				if (((previousValue != value) 
							|| (this._TBL_CONS_DPT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_CONS_DPT.Entity = null;
						previousValue.TBL_DOCs.Remove(this);
					}
					this._TBL_CONS_DPT.Entity = value;
					if ((value != null))
					{
						value.TBL_DOCs.Add(this);
						this._ID_IDENTIFICADOR = value.ID_IDENTIFICADOR;
					}
					else
					{
						this._ID_IDENTIFICADOR = default(string);
					}
					this.SendPropertyChanged("TBL_CONS_DPT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_DPTS")]
	public partial class TBL_DPT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_DPTO;
		
		private string _DESCRIP;
		
		private int _ID_DIRECCION;
		
		private string _CREATEBY_DPT;
		
		private string _UPDATEBY_DPT;
		
		private bool _STATE_DPT;
		
		private System.DateTime _CREATEDATE_DPT;
		
		private EntitySet<TBL_CONS_DPT> _TBL_CONS_DPTs;
		
		private EntitySet<TBL_USUARIO> _TBL_USUARIOs;
		
		private EntityRef<TBL_DIRECCIONE> _TBL_DIRECCIONE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DPTOChanging(int value);
    partial void OnID_DPTOChanged();
    partial void OnDESCRIPChanging(string value);
    partial void OnDESCRIPChanged();
    partial void OnID_DIRECCIONChanging(int value);
    partial void OnID_DIRECCIONChanged();
    partial void OnCREATEBY_DPTChanging(string value);
    partial void OnCREATEBY_DPTChanged();
    partial void OnUPDATEBY_DPTChanging(string value);
    partial void OnUPDATEBY_DPTChanged();
    partial void OnSTATE_DPTChanging(bool value);
    partial void OnSTATE_DPTChanged();
    partial void OnCREATEDATE_DPTChanging(System.DateTime value);
    partial void OnCREATEDATE_DPTChanged();
    #endregion
		
		public TBL_DPT()
		{
			this._TBL_CONS_DPTs = new EntitySet<TBL_CONS_DPT>(new Action<TBL_CONS_DPT>(this.attach_TBL_CONS_DPTs), new Action<TBL_CONS_DPT>(this.detach_TBL_CONS_DPTs));
			this._TBL_USUARIOs = new EntitySet<TBL_USUARIO>(new Action<TBL_USUARIO>(this.attach_TBL_USUARIOs), new Action<TBL_USUARIO>(this.detach_TBL_USUARIOs));
			this._TBL_DIRECCIONE = default(EntityRef<TBL_DIRECCIONE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DPTO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_DPTO
		{
			get
			{
				return this._ID_DPTO;
			}
			set
			{
				if ((this._ID_DPTO != value))
				{
					this.OnID_DPTOChanging(value);
					this.SendPropertyChanging();
					this._ID_DPTO = value;
					this.SendPropertyChanged("ID_DPTO");
					this.OnID_DPTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DESCRIP
		{
			get
			{
				return this._DESCRIP;
			}
			set
			{
				if ((this._DESCRIP != value))
				{
					this.OnDESCRIPChanging(value);
					this.SendPropertyChanging();
					this._DESCRIP = value;
					this.SendPropertyChanged("DESCRIP");
					this.OnDESCRIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DIRECCION", DbType="Int NOT NULL")]
		public int ID_DIRECCION
		{
			get
			{
				return this._ID_DIRECCION;
			}
			set
			{
				if ((this._ID_DIRECCION != value))
				{
					if (this._TBL_DIRECCIONE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_DIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._ID_DIRECCION = value;
					this.SendPropertyChanged("ID_DIRECCION");
					this.OnID_DIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEBY_DPT", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string CREATEBY_DPT
		{
			get
			{
				return this._CREATEBY_DPT;
			}
			set
			{
				if ((this._CREATEBY_DPT != value))
				{
					this.OnCREATEBY_DPTChanging(value);
					this.SendPropertyChanging();
					this._CREATEBY_DPT = value;
					this.SendPropertyChanged("CREATEBY_DPT");
					this.OnCREATEBY_DPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATEBY_DPT", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string UPDATEBY_DPT
		{
			get
			{
				return this._UPDATEBY_DPT;
			}
			set
			{
				if ((this._UPDATEBY_DPT != value))
				{
					this.OnUPDATEBY_DPTChanging(value);
					this.SendPropertyChanging();
					this._UPDATEBY_DPT = value;
					this.SendPropertyChanged("UPDATEBY_DPT");
					this.OnUPDATEBY_DPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_DPT", DbType="Bit NOT NULL")]
		public bool STATE_DPT
		{
			get
			{
				return this._STATE_DPT;
			}
			set
			{
				if ((this._STATE_DPT != value))
				{
					this.OnSTATE_DPTChanging(value);
					this.SendPropertyChanging();
					this._STATE_DPT = value;
					this.SendPropertyChanged("STATE_DPT");
					this.OnSTATE_DPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE_DPT", DbType="DateTime NOT NULL")]
		public System.DateTime CREATEDATE_DPT
		{
			get
			{
				return this._CREATEDATE_DPT;
			}
			set
			{
				if ((this._CREATEDATE_DPT != value))
				{
					this.OnCREATEDATE_DPTChanging(value);
					this.SendPropertyChanging();
					this._CREATEDATE_DPT = value;
					this.SendPropertyChanged("CREATEDATE_DPT");
					this.OnCREATEDATE_DPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_DPT_TBL_CONS_DPT", Storage="_TBL_CONS_DPTs", ThisKey="ID_DPTO", OtherKey="ID_DPTO")]
		public EntitySet<TBL_CONS_DPT> TBL_CONS_DPTs
		{
			get
			{
				return this._TBL_CONS_DPTs;
			}
			set
			{
				this._TBL_CONS_DPTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_DPT_TBL_USUARIO", Storage="_TBL_USUARIOs", ThisKey="ID_DPTO", OtherKey="ID_DPTO")]
		public EntitySet<TBL_USUARIO> TBL_USUARIOs
		{
			get
			{
				return this._TBL_USUARIOs;
			}
			set
			{
				this._TBL_USUARIOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_DIRECCIONE_TBL_DPT", Storage="_TBL_DIRECCIONE", ThisKey="ID_DIRECCION", OtherKey="ID_DIRECCION", IsForeignKey=true)]
		public TBL_DIRECCIONE TBL_DIRECCIONE
		{
			get
			{
				return this._TBL_DIRECCIONE.Entity;
			}
			set
			{
				TBL_DIRECCIONE previousValue = this._TBL_DIRECCIONE.Entity;
				if (((previousValue != value) 
							|| (this._TBL_DIRECCIONE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_DIRECCIONE.Entity = null;
						previousValue.TBL_DPTs.Remove(this);
					}
					this._TBL_DIRECCIONE.Entity = value;
					if ((value != null))
					{
						value.TBL_DPTs.Add(this);
						this._ID_DIRECCION = value.ID_DIRECCION;
					}
					else
					{
						this._ID_DIRECCION = default(int);
					}
					this.SendPropertyChanged("TBL_DIRECCIONE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TBL_CONS_DPTs(TBL_CONS_DPT entity)
		{
			this.SendPropertyChanging();
			entity.TBL_DPT = this;
		}
		
		private void detach_TBL_CONS_DPTs(TBL_CONS_DPT entity)
		{
			this.SendPropertyChanging();
			entity.TBL_DPT = null;
		}
		
		private void attach_TBL_USUARIOs(TBL_USUARIO entity)
		{
			this.SendPropertyChanging();
			entity.TBL_DPT = this;
		}
		
		private void detach_TBL_USUARIOs(TBL_USUARIO entity)
		{
			this.SendPropertyChanging();
			entity.TBL_DPT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_USUARIOS")]
	public partial class TBL_USUARIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_USER;
		
		private string _NOMBREC_USER;
		
		private string _APELLIDO1_USER;
		
		private string _APELLIDO2_USER;
		
		private string _CORREO_USER;
		
		private string _TELEFONO_USER;
		
		private int _ID_ROLE;
		
		private int _ID_DPTO;
		
		private string _CREATEBY_USER;
		
		private string _UPDATEBY_USER;
		
		private bool _STATE_USER;
		
		private System.DateTime _CREATEDATE_USER;
		
		private EntityRef<TBL_DPT> _TBL_DPT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_USERChanging(string value);
    partial void OnID_USERChanged();
    partial void OnNOMBREC_USERChanging(string value);
    partial void OnNOMBREC_USERChanged();
    partial void OnAPELLIDO1_USERChanging(string value);
    partial void OnAPELLIDO1_USERChanged();
    partial void OnAPELLIDO2_USERChanging(string value);
    partial void OnAPELLIDO2_USERChanged();
    partial void OnCORREO_USERChanging(string value);
    partial void OnCORREO_USERChanged();
    partial void OnTELEFONO_USERChanging(string value);
    partial void OnTELEFONO_USERChanged();
    partial void OnID_ROLEChanging(int value);
    partial void OnID_ROLEChanged();
    partial void OnID_DPTOChanging(int value);
    partial void OnID_DPTOChanged();
    partial void OnCREATEBY_USERChanging(string value);
    partial void OnCREATEBY_USERChanged();
    partial void OnUPDATEBY_USERChanging(string value);
    partial void OnUPDATEBY_USERChanged();
    partial void OnSTATE_USERChanging(bool value);
    partial void OnSTATE_USERChanged();
    partial void OnCREATEDATE_USERChanging(System.DateTime value);
    partial void OnCREATEDATE_USERChanged();
    #endregion
		
		public TBL_USUARIO()
		{
			this._TBL_DPT = default(EntityRef<TBL_DPT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USER", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_USER
		{
			get
			{
				return this._ID_USER;
			}
			set
			{
				if ((this._ID_USER != value))
				{
					this.OnID_USERChanging(value);
					this.SendPropertyChanging();
					this._ID_USER = value;
					this.SendPropertyChanged("ID_USER");
					this.OnID_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBREC_USER", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBREC_USER
		{
			get
			{
				return this._NOMBREC_USER;
			}
			set
			{
				if ((this._NOMBREC_USER != value))
				{
					this.OnNOMBREC_USERChanging(value);
					this.SendPropertyChanging();
					this._NOMBREC_USER = value;
					this.SendPropertyChanged("NOMBREC_USER");
					this.OnNOMBREC_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDO1_USER", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string APELLIDO1_USER
		{
			get
			{
				return this._APELLIDO1_USER;
			}
			set
			{
				if ((this._APELLIDO1_USER != value))
				{
					this.OnAPELLIDO1_USERChanging(value);
					this.SendPropertyChanging();
					this._APELLIDO1_USER = value;
					this.SendPropertyChanged("APELLIDO1_USER");
					this.OnAPELLIDO1_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDO2_USER", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string APELLIDO2_USER
		{
			get
			{
				return this._APELLIDO2_USER;
			}
			set
			{
				if ((this._APELLIDO2_USER != value))
				{
					this.OnAPELLIDO2_USERChanging(value);
					this.SendPropertyChanging();
					this._APELLIDO2_USER = value;
					this.SendPropertyChanged("APELLIDO2_USER");
					this.OnAPELLIDO2_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO_USER", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string CORREO_USER
		{
			get
			{
				return this._CORREO_USER;
			}
			set
			{
				if ((this._CORREO_USER != value))
				{
					this.OnCORREO_USERChanging(value);
					this.SendPropertyChanging();
					this._CORREO_USER = value;
					this.SendPropertyChanged("CORREO_USER");
					this.OnCORREO_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO_USER", DbType="VarChar(15)")]
		public string TELEFONO_USER
		{
			get
			{
				return this._TELEFONO_USER;
			}
			set
			{
				if ((this._TELEFONO_USER != value))
				{
					this.OnTELEFONO_USERChanging(value);
					this.SendPropertyChanging();
					this._TELEFONO_USER = value;
					this.SendPropertyChanged("TELEFONO_USER");
					this.OnTELEFONO_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ROLE", DbType="Int NOT NULL")]
		public int ID_ROLE
		{
			get
			{
				return this._ID_ROLE;
			}
			set
			{
				if ((this._ID_ROLE != value))
				{
					this.OnID_ROLEChanging(value);
					this.SendPropertyChanging();
					this._ID_ROLE = value;
					this.SendPropertyChanged("ID_ROLE");
					this.OnID_ROLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DPTO", DbType="Int NOT NULL")]
		public int ID_DPTO
		{
			get
			{
				return this._ID_DPTO;
			}
			set
			{
				if ((this._ID_DPTO != value))
				{
					if (this._TBL_DPT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_DPTOChanging(value);
					this.SendPropertyChanging();
					this._ID_DPTO = value;
					this.SendPropertyChanged("ID_DPTO");
					this.OnID_DPTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEBY_USER", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string CREATEBY_USER
		{
			get
			{
				return this._CREATEBY_USER;
			}
			set
			{
				if ((this._CREATEBY_USER != value))
				{
					this.OnCREATEBY_USERChanging(value);
					this.SendPropertyChanging();
					this._CREATEBY_USER = value;
					this.SendPropertyChanged("CREATEBY_USER");
					this.OnCREATEBY_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATEBY_USER", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string UPDATEBY_USER
		{
			get
			{
				return this._UPDATEBY_USER;
			}
			set
			{
				if ((this._UPDATEBY_USER != value))
				{
					this.OnUPDATEBY_USERChanging(value);
					this.SendPropertyChanging();
					this._UPDATEBY_USER = value;
					this.SendPropertyChanged("UPDATEBY_USER");
					this.OnUPDATEBY_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_USER", DbType="Bit NOT NULL")]
		public bool STATE_USER
		{
			get
			{
				return this._STATE_USER;
			}
			set
			{
				if ((this._STATE_USER != value))
				{
					this.OnSTATE_USERChanging(value);
					this.SendPropertyChanging();
					this._STATE_USER = value;
					this.SendPropertyChanged("STATE_USER");
					this.OnSTATE_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE_USER", DbType="DateTime NOT NULL")]
		public System.DateTime CREATEDATE_USER
		{
			get
			{
				return this._CREATEDATE_USER;
			}
			set
			{
				if ((this._CREATEDATE_USER != value))
				{
					this.OnCREATEDATE_USERChanging(value);
					this.SendPropertyChanging();
					this._CREATEDATE_USER = value;
					this.SendPropertyChanged("CREATEDATE_USER");
					this.OnCREATEDATE_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TBL_DPT_TBL_USUARIO", Storage="_TBL_DPT", ThisKey="ID_DPTO", OtherKey="ID_DPTO", IsForeignKey=true)]
		public TBL_DPT TBL_DPT
		{
			get
			{
				return this._TBL_DPT.Entity;
			}
			set
			{
				TBL_DPT previousValue = this._TBL_DPT.Entity;
				if (((previousValue != value) 
							|| (this._TBL_DPT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TBL_DPT.Entity = null;
						previousValue.TBL_USUARIOs.Remove(this);
					}
					this._TBL_DPT.Entity = value;
					if ((value != null))
					{
						value.TBL_USUARIOs.Add(this);
						this._ID_DPTO = value.ID_DPTO;
					}
					else
					{
						this._ID_DPTO = default(int);
					}
					this.SendPropertyChanged("TBL_DPT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
